### ISSUE TITLE
Hi, do you have discord account so we can discuss about webpack?

### ISSUE THREAD

**Issue by nyngwang** [cwj0417/webpack-explorer#1]
As title. I can speak Chinese.

**Comment by cwj0417** [comment]
chenwj2596

**Comment by cwj0417** [comment]
hi, and you are chinese, my wechat account is jun_wen_chen

**Comment by nyngwang** [comment]
@cwj0417 Sent. Let me close this thread and you might want to delete both of your comments (in case some random people might add you) :)
